{
  lib,
  callPackage,
}:

# Forge server packages.
#
# Each attribute is built from a lock in ./locks, generated by
# update.py. The lock records every artifact the installer needs,
# so installation happens entirely at build time: no network access, and no
# first-run install step.
let
  lockDir = ./locks;

  locks = lib.filterAttrs
    (n: t: t == "regular" && lib.hasSuffix ".json" n)
    (builtins.readDir lockDir);

  # locks/forge-<mc>-<forge>.json -> { mc; forge; }. Forge builds for old
  # Minecraft versions carry a hyphen in the loader version (e.g.
  # 1.7.10-10.13.4.1614-1.7.10), so the loader part allows further hyphenated
  # numeric segments. builtins.match is POSIX ERE, hence no `(?:...)`.
  parseName =
    name:
    let
      m = builtins.match "forge-([0-9.]+)-([0-9]+[.0-9-]*)\\.json" name;
    in
    if m == null then null else { mc = builtins.elemAt m 0; forge = builtins.elemAt m 1; };

  entries = lib.filter (e: e != null) (lib.mapAttrsToList (name: _: parseName name) locks);

  mk = e: callPackage ./derivation.nix { lock = lockDir + "/forge-${e.mc}-${e.forge}.json"; };

  # Same escaping nix-minecraft's lib.our uses; defined locally so this tree
  # does not depend on nix-minecraft's lib extension.
  escapeVersion = lib.replaceStrings [ "." " " ] [ "_" "_" ];
in
lib.recurseIntoAttrs (builtins.listToAttrs (
  (map
    (e: {
      name = "forge-${escapeVersion e.mc}";
      value = mk e;
    })
    entries)
  ++ (map
    (e: {
      name = "forge-${escapeVersion e.mc}-${escapeVersion e.forge}";
      value = mk e;
    })
    entries)
))
