{
  pkgs,
  lib,
  fetchurl,
  jre8,
  jre_headless,
  makeWrapper,
  python3,
  stdenvNoCC,
  strip-nondeterminism,
  unzip,

  # Path to a lock generated by update.py
  lock,
}:
let
  l = builtins.fromJSON (builtins.readFile lock);
  version = "${l.mc}-${l.forge}";
  forgeDir = "net/minecraftforge/forge/${version}";

  # spec 0: `java -jar forge-<v>.jar`, Java 8
  # spec 1: `@unix_args.txt` via BootstrapLauncher, modern Java
  #
  # Older generations (<= 1.12) are not supported yet: their libraries are
  # split across two Mavens and carry no download info, so lock generation
  # needs a resolver that has not been written.
  modern = (l.spec or 0) >= 1;
  runtimeJava = if modern then jre_headless else jre8;

  installer = fetchurl {
    url = "https://maven.minecraftforge.net/net/minecraftforge/forge/${version}/forge-${version}-installer.jar";
    hash = l.installerSha256;
  };

  # Jars that ship inside the installer rather than on a Maven repository.
  bundled = lib.filterAttrs (_: a: lib.hasPrefix "bundle:" a.url) l.libraries;
  repoLibs = lib.filterAttrs (_: a: !(lib.hasPrefix "bundle:" a.url)) l.libraries;

  vanilla = l.libraries."net.minecraft:server:${l.mc}";

  # Every artifact the install needs, laid out in Maven repository form.
  #
  # The Mojang mappings are included because the processor that would normally
  # download them is skipped: mappings are content-addressed on piston-meta, so
  # fetchurl pins them exactly. The vanilla server jar likewise satisfies
  # MINECRAFT_JAR without any version-manifest lookup.
  libraries = pkgs.linkFarm "forge-${version}-libraries" (
    (lib.mapAttrsToList (_: a: {
      name = a.path;
      path = fetchurl {
        inherit (a) url;
        sha1 = a.sha1;
      };
    }) repoLibs)
    ++ (lib.optional (l.mojmaps != null) {
      name = l.mojmaps.path;
      path = fetchurl {
        inherit (l.mojmaps) url sha1;
      };
    })
    ++ [
      {
        name = "net/minecraft/server/${l.mc}/server-${l.mc}.jar";
        path = fetchurl {
          inherit (vanilla) url sha1;
        };
      }
    ]
  );
in
stdenvNoCC.mkDerivation {
  pname = "forge";
  inherit version;

  dontUnpack = true;
  nativeBuildInputs = [
    # The install tools always run on a modern JRE; only the server itself is
    # pinned to an older Java where the loader requires it.
    jre_headless
    makeWrapper
    python3
    unzip
  ] ++ lib.optionals (!modern) [ strip-nondeterminism ];

  buildCommand = ''
    mkdir -p $out/libraries
    cp -r --no-preserve=all ${libraries}/* $out/libraries/

    ${lib.optionalString (bundled != { }) ''
      # Some jars ship inside the installer rather than on a Maven repo. The
      # Forge universal jar is bundled this way for older versions.
      ${builtins.concatStringsSep "\n" (
        lib.mapAttrsToList (_: a: ''
          mkdir -p "$out/libraries/$(dirname ${a.path})"
          unzip -p ${installer} ${lib.removePrefix "bundle:" a.url} > "$out/libraries/${a.path}"
        '') bundled
      )}
    ''}

    ${lib.optionalString (!modern) ''
      # spec 0 resolves MINECRAFT_JAR to {ROOT}/minecraft_server.{MC}.jar.
      cp "$out/libraries/net/minecraft/server/${l.mc}/server-${l.mc}.jar" \
         "$out/minecraft_server.${l.mc}.jar"

      # The launcher jar is normally copied out to the target root by
      # ServerInstall. Its manifest Class-Path entries resolve relative to the
      # jar rather than the cwd, so the server can start from any data
      # directory afterwards.
      cp "$out/libraries/${forgeDir}/forge-${version}.jar" \
         "$out/forge-${version}.jar"
    ''}

    # Extract the profile and run its processors directly, rather than
    # delegating to `java -jar installer.jar --installServer`.
    #
    # Going through SimpleInstaller would require editing install_profile.json
    # inside the jar to stop DOWNLOAD_MOJMAPS from calling out to
    # launchermeta.mojang.com. The obvious flag for that, --skipIfExists, only
    # exists in installertools >= 1.4.1; Forge 1.18.x ships 1.3.0 and rejects
    # it with UnrecognizedOptionException. Running the processors ourselves
    # needs no jar modification at all, and each step stays inspectable.
    unzip -p ${installer} install_profile.json > $TMPDIR/install_profile.json

    export JAVA=${jre_headless}/bin/java
    python3 ${./run-processors.py} \
      $TMPDIR/install_profile.json \
      "$out/libraries" \
      ${installer} \
      "$out" \
      server

    # Fail loudly if the primary output does not match the SHA-1 Forge
    # published for it. The expected value comes from install_profile.json, so
    # this is an upstream-provided check rather than a self-generated one.
    #
    # spec 1 records the hash of the patched server jar (PATCHED_SHA). spec 0
    # has no equivalent, so the launcher jar's declared sha1 is used instead.
    expect_sha1() {
      actual=$(sha1sum "$1" | cut -d' ' -f1)
      if [ "$actual" != "$2" ]; then
        echo "FATAL: $(basename "$1") does not match the SHA-1 declared by Forge" >&2
        echo "  expected $2" >&2
        echo "  actual   $actual" >&2
        exit 1
      fi
    }

    ${lib.optionalString (l.patchedSha != null) ''
      expect_sha1 "$out/libraries/${forgeDir}/forge-${version}-server.jar" "${l.patchedSha}"
    ''}

    ${lib.optionalString (l.patchedSha == null) ''
      expect_sha1 "$out/libraries/${forgeDir}/forge-${version}.jar" "${l.libraries."net.minecraftforge:forge:${version}".sha1}"
    ''}

    # Drop install-time residue: the jarsplitter inputs, both mapping tables,
    # the installer tools, the vanilla bundler, and every library symlink the
    # launch surface does not read. For 1.20.1 that is ~37 files and 91 MiB,
    # plus the store paths those symlinks were keeping alive.
    mkdir -p $out/bin

    ${lib.optionalString modern ''
      # Forge resolves its libraries through a `libraryDirectory` system
      # property and a legacyClassPath whose entries are relative to the
      # process working directory. Point both at $out so the server works
      # from any cwd. The no-trailing-slash form must be fixed first,
      # otherwise the blanket rewrite below misses it.
      args="$out/libraries/${forgeDir}/unix_args.txt"
      substituteInPlace "$args" \
        --replace-fail "-DlibraryDirectory=libraries" "-DlibraryDirectory=$out/libraries" \
        --replace-fail "libraries/" "$out/libraries/"

      makeWrapper ${runtimeJava}/bin/java $out/bin/forge-server \
        --add-flags "@$args"
    ''}

    ${lib.optionalString (!modern) ''
      # spec 0 launch: the launcher jar sits at the target root.
      rootJar="$out/forge-${version}.jar"
      if [ ! -f "$rootJar" ]; then
        echo "FATAL: expected launcher jar $rootJar" >&2
        ls -la "$out" >&2
        exit 1
      fi

      makeWrapper ${runtimeJava}/bin/java $out/bin/forge-server \
        --add-flags "-jar" \
        --add-flags "$rootJar"
    ''}

    # Drop install-time residue and the library symlinks nothing reads.
    #
    # Runs *after* the SHA check above, since one of the things it removes is
    # the jarsplitter output that check compares against PATCHED_SHA, and after
    # the wrapper is written, so that `bin/forge-server` is part of the launch
    # surface it verifies.
    #
    # prune.py re-derives that surface from the freshly built tree and asserts
    # every entry still exists, so a Forge version that needs something removed
    # here fails the build instead of producing a server that dies at startup.
    python3 ${./prune.py} \
      $TMPDIR/install_profile.json \
      "$out" \
      server \
      ${if modern then "spec1" else "spec0"}

    ${lib.optionalString (!modern) ''
      # ForgeAutoRenamingTool records the *current time* in the zip entries of
      # the jar it emits. That alone made 1.16.5 non-reproducible: `--rebuild`
      # reported a difference although the contents were identical, which was
      # confirmed by normalising both builds' timestamps and comparing digests.
      # It is a Forge artifact, not something this derivation introduces -- the
      # same check fails on the version without prune.py.
      #
      # Only spec0 needs this. The spec1 output comes from binarypatcher, which
      # writes no timestamps, and its `--rebuild` was already clean.
      #
      # Safe for a server jar: timestamps inside a nested jar are not read, and
      # the class files keep their own compilation metadata -- unlike a .apk or
      # .deb, where the archive timestamp is meaningful.
      find "$out" -name '*.jar' -exec strip-nondeterminism {} +
    ''}
  '';

  passthru = {
    inherit
      installer
      libraries
      runtimeJava
      ;
    gameVersion = l.mc;
    loaderVersion = l.forge;
    inherit (l) generation;
  };

  meta = {
    description = "Minecraft Forge server ${l.mc}";
    homepage = "https://minecraftforge.net";
    license = lib.licenses.unfreeRedistributable;
    platforms = lib.platforms.unix;
    mainProgram = "forge-server";
  };
}
